const expectVisuals = @import("usage_tests1.zig").expectVisuals;

test "basic usage" {
    try expectVisuals(
        \\2: {Rc8+}{Rg1+}
    ,
        \\
        \\rook *Checks king *becomes rook2
        \\
    ,
        \\......k.
        \\........
        \\........
        \\........
        \\........
        \\........
        \\........
        \\..r.....
    );
}
