const std = @import("std");
const testing = std.testing;
const Allocator = std.mem.Allocator;
const chess = @import("chess/types.zig");
const DotUsage = @import("usage.zig").DotUsage;

fn expectVisuals(expected: []const u8, script: []const u8, position: *const [71:0]u8) !void {
    const ally = testing.allocator;

    var usage = try DotUsage.init(ally, script);
    defer usage.deinit(ally);

    try usage.runner.runOnPosition(ally, chess.Parses.white(position));

    try std.testing.expectEqualStrings(expected, try usage.printLines(ally));
}

test "pawn captures" {
    try expectVisuals(
        \\2: {dxe4}{exd3}
    ,
        \\
        \\pawn *Captures pawn2 *becomes pawn3
        \\
    ,
        \\........
        \\........
        \\........
        \\........
        \\....p...
        \\...P....
        \\........
        \\........
    );
}

test "bishop captures" {
    try expectVisuals(
        \\2: {Bxe4}
    ,
        \\
        \\bishop *Captures pawn *becomes bishop2
        \\
    ,
        \\........
        \\........
        \\..b.....
        \\........
        \\....p...
        \\...P....
        \\........
        \\........
    );
}

test "multi line" {
    try expectVisuals(
        \\2: {Bxe4}
        \\3: {Bxe4 dxe4}
    ,
        \\
        \\bishop *Captures pawn *becomes bishop2
        \\pawn2 *Captures bishop2 *becomes pawn3
        \\
    ,
        \\........
        \\........
        \\..b.....
        \\........
        \\....p...
        \\...P....
        \\........
        \\........
    );
}
